### ISSUE TITLE
Change "YES" to "Success"?

### ISSUE THREAD

**Issue by dddlr** [vaxxnz/vaxxed-as-web#22]
The word "yes" is a bit vague. It seems like the intention was that it would be an answer to a closed question (presumably "does this person have a valid vaccine pass?"), but the way it's presented in the UI with confetti suggests that it's a celebration of joy (like "Yes!"), which is something else entirely.

Maybe something like "Success" might be a bit clearer?

Using a different word also avoids the awkward situation of having to adapt the word "yes", an incredibly context-sensitive word, into other languages. For example, in Chinese there's at least ten potential direct translations for "yes", none of which seems particularly appropriate in this context - which was why I suggested 成功 ("success") for the Chinese translations on Localazy.

**Comment by rafcontreras** [comment]
I would then suggest `Valid` instead. What do you think @dddlr ?

**Comment by dddlr** [comment]
Sounds good!

**Comment by rafcontreras** [comment]
Fixed on [this PR](https://github.com/vaxxnz/vaxxed-as-web/pull/24)
