### ISSUE TITLE
Integration with handheld 2d scanners 

### ISSUE THREAD

**Issue by wing5wong** [vaxxnz/vaxxed-as-web#26]
Is it possible to utilise a handheld scanner in addition to the camera for online scans? 
an input field of some form instead of the camera

We would like to add this to an office area without the requirement for a seperate device to install the app on

Something like this https://www.honeywellaidc.com/en-au/products/barcode-scanners/handheld/hh400

**Comment by rafcontreras** [comment]
Hi @wing5wong, I've added that functionality, it is available now at https://vaxxed.as/input
